### ISSUE TITLE
Prettier とかでコードをきれいにする

### ISSUE THREAD

**Issue by huequica** [Assault1892/discord-replace-twitter-link#4]
コードフォーマッタあったほうがいい感ある。
あと自動整形されるので管理ラク。
あとは ESLint を入れるかどうかも検討。

**Comment by huequica** [comment]
@Assault1892 
あとで叩き台のPR出しておくわ( huequica/pkfire で適当に作っておく)

**Comment by Assault1892** [comment]
お、ありがとう〜
